version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::705576196689:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-mxVABcZdZsFj"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::705576196689:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-h6yxigo22O0U"
cloudformation_execution_role = "arn:aws:iam::705576196689:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-PSxVnuSdSlxm"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-jl6aejc8kzes"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::705576196689:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-OGBnnhww2D3E"
cloudformation_execution_role = "arn:aws:iam::705576196689:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-81xUCbcEu7O5"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-api9e1svgeae"
image_repository = ""
region = "us-east-1"
